# Generated by Django 3.2.5 on 2021-07-18 04:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WeightTracker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=256)),
                ('first_name', models.CharField(max_length=256, null=True)),
                ('last_name', models.CharField(max_length=256, null=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='weighttracker', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Weight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_type', models.CharField(choices=[('Weight Gain', 'weight gain'), ('Weight Loss', 'weight loss')], default='Weight Loss', max_length=20, verbose_name='Account Type')),
                ('target_weight', models.FloatField(default=0, max_length=20, verbose_name='Enter your target weight')),
                ('finish_date', models.DateField(null=True)),
                ('topic', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='weights', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=256, null=True)),
                ('last_name', models.CharField(max_length=256, null=True)),
                ('age', models.PositiveIntegerField()),
                ('user_gender', models.CharField(blank=True, choices=[('Male', 'Male'), ('Female', 'Female')], default='Male', max_length=15, verbose_name='Gender')),
                ('height', models.FloatField(default=0, max_length=20, verbose_name='Enter your height')),
                ('user_photo', models.ImageField(blank=True, upload_to='WeightTrackers/media/')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='profiles', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Calculate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bmi', models.FloatField(default=0, max_length=20, verbose_name='Body Mass Index')),
                ('calorie', models.FloatField(default=0, max_length=20, verbose_name='Calorie')),
                ('entry_date', models.DateField(auto_now_add=True, null=True)),
                ('weight', models.FloatField(default=0, max_length=20, verbose_name='Weight')),
                ('weight_difference', models.FloatField(default=0, max_length=20, verbose_name='Weight Loss')),
                ('topic', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='calculates', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='AddWeight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('add_weight', models.FloatField(default=0, max_length=20, verbose_name='Enter your weight:')),
                ('topic', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='add_weight', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Activities',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('add_activity', models.TextField(blank=True)),
                ('activity_level', models.CharField(blank=True, choices=[('Sedentary', 'Sedentary'), ('Lightly active', 'Lightly active'), ('Moderately active', 'Moderately active'), ('Very active', 'Very active'), ('Extra active', 'Extra active')], default='Lightly active', help_text='Sedentary: Little or no exercise.  \nLightly active: Light exercise/sports 1-3 days/week. \nModerately active: Moderate exercise/sports 3-5 days/week.\nVery active: Hard exercise/sports 6-7 days/week.\nExtra active: Very hard exercise/sports and physical job', max_length=100, verbose_name='Activity intensity')),
                ('topic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
