# Generated by Django 3.2.5 on 2021-07-16 04:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('WeightTrackers', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='weighttracker',
            old_name='username',
            new_name='user',
        ),
    ]
