# Generated by Django 3.2.5 on 2021-07-18 05:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('WeightTrackers', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='weighttracker',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='weighttracker',
            name='last_name',
        ),
        migrations.RemoveField(
            model_name='weighttracker',
            name='username',
        ),
    ]
