# Generated by Django 3.2.5 on 2021-08-01 22:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WeightTrackers', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='user_photo',
            field=models.ImageField(blank=True, null=True, upload_to='WeightTrackers/media/'),
        ),
    ]
